### ISSUE TITLE
assets:clean / webpacker:clean task deletes the latest version of files when asset_host is set

### ISSUE THREAD

**Issue by robotfelix** [shakacode/shakapacker#151] opened 2022-06-29 16:12 UTC
Ruby version: 2.7.6
Rails version: 6.1.6
Webpacker version: 6.4.1

### Expected behavior:

As documented by [a comment in the implementation file itself](https://github.com/shakacode/shakapacker/blob/3ba9970e2d3addb7aae980d97c6ab4527f8e55f8/lib/webpacker/commands.rb#L8-L9), running the `webpacker:clean` task (or the enhanced `assets:clean` task) should _**always**_ keep the latest version of compiled assets as indicated by _manifest.json_.

There is no expectation that setting `config.asset_host` (or the longer name of `config.action_controller.asset_host`) in _production.rb_ should change this behaviour.

### Actual behavior:

If a host is set for `config.asset_host`, then the `webpacker:clean` task will sometimes remove even the latest version of assets, leading to 404s for those assets. I think this is down to the age of the asset file.

### Steps to reproduce:

1. Set `config.asset_host` to any host in _production.rb_, eg `config.asset_host = example.com`
2. Run `RAILS_ENV=production bundle exec rails assets:precompile`
3. Wait 1 second
4. Run RAILS_ENV=production bundle exec rake webpacker:clean[2,1]
5. See that all your new assets just got removed!

(To save you from looking, the '1' argument in the command sets the maximum age of assets that are no longer considered the "latest" version to 1 second.)

### Cause:

Setting `config.asset_host` causes full URLs to be inserted into the _manifest.json_, eg:
```js
{
  // ... other assets ...
  "application.js": "//example.com/packs/js/application-50abb05db229c31c1e24.js",
  // ... other assets ...
}
```
which is already [documented in the troubleshooting docs](https://github.com/shakacode/shakapacker/blob/3ba9970e2d3addb7aae980d97c6ab4527f8e55f8/docs/troubleshooting.md#wrong-cdn-src-from-javascript_pack_tag) relating to another issue.

I couldn't locate the PR/motivation for this change to _manifest.json_, but as a reminder, prior to shakapacker/webpacker v6 manifest.json did not include the asset_host.

Unfortunately the implementation of `webpacker:clean` was not updated to handle this, so it is expecting to get local file paths but getting remote URLs from _manifest.json_. Since none of the local assets paths match the remote URLs, this in turns means that no local assets are kept due to being the current version, and they are only ever kept if they meet the criteria for keeping a backup.
https://github.com/shakacode/shakapacker/blob/3ba9970e2d3addb7aae980d97c6ab4527f8e55f8/lib/webpacker/commands.rb#L69-L78

In particular, on line 74 `value` is a URL so sticking this on the end of the project root path produces a half-local-path half-URL string.

### Workaround:

Like the linked troubleshooting issue, setting the `WEBPACKER_ASSET_HOST` env variable to an empty string causes the _manifest.json_ to revert to having relative paths, so the `webpacker:clean` task then works correctly.

### Thoughts on priority:

This is quite a nasty issue as things might work absolutely fine when initially upgrading to shakapacker, but then start failing in weird ways on subsequent builds.

You can get very strange behaviours since all of the logic is based off of the file age, so in my case running `assets:clean` removed a `foo.js` file while leaving the equivalent `foo.js.gz` file intact, causing much head scratching due things working in some browsers and not others.

**Comment by tomdracz** [comment] 2022-06-30 09:46
Thanks for raising. I was surprised by:

> I couldn't locate the PR/motivation for this change to manifest.json, but as a reminder, prior to shakapacker/webpacker v6 manifest.json did not include the asset_host.

But it might have been caused by https://github.com/rails/webpacker/pull/2802

https://github.com/shakacode/shakapacker/blob/master/package/environments/base.js#L66 this line used to pass in path without CDN https://github.com/shakacode/shakapacker/commit/b041a1d3e53c55ad801654892c99f5ec4ff099f2

https://github.com/rails/webpacker/pull/1974 - that might be the missing piece here but will need to dig into this further to figure out how it all ties together

**Comment by robotfelix** [comment] 2022-06-30 09:56
It's probably not too difficult (famous last words) to update the implementation of `current_version` to trim off any `asset_host` (or `WEBPACKER_ASSET_HOST` if set) from the manifest values, which would fix this issue.

However since the change to `manifest.json` is the source of at least one other troubleshooting issue, it does seem like understanding the rationale behind the change would be useful!

**Comment by tomdracz** [comment] 2022-06-30 10:08
Agree, trimming the host from clean task would be a quick solution, but I do want to trace the changes to figure out what's what. The change linked happened in unreleased Webpacker v6 so I'll just need to trace down the commits and figure out how it worked before, to mimic the same setup!

**Comment by Judahmeek** [comment] 2022-12-28 17:28
@ahangarha this is actually a fairly serious issue.

**Comment by jschroe212** [comment] 2023-08-02 19:31
For my application, forcing SHAKAPACKER_ASSET_HOST="" was a solution, but I believe that depends on the application.  We only referenced WebPack image assets from within CSS files. Since the CSS file was included by javascript_pack_tag, it included the CDN hostname. The CSS file then had relative URLs resolved by Webpack and the browser requested them with the same CDN host, and everything worked as expected. 

Now see the following comment from webpacker: https://github.com/rails/webpacker/issues/1845#issuecomment-469049916

If an application resolves assets like this and uses them in templates or some other similar manner in javascript at runtime, then with the way this was set up with webpack, SHAKAPACKER_ASSET_HOST would need to be set at compile time.  Webpack output.publicPath gets set to include SHAKAPACKER_ASSET_HOST, and the webpack-assets-manifest.publicPath option defaults to true so the CDN is then included in the manifest file. 

Another commenter brought up the following comment: https://github.com/rails/webpacker/pull/1974/files#diff-7af8667a3e36201db57c02b68dd8651883d7bfc00dc9653661be11cd31feeccd

Setting WebPackAssetsManifest.publicPath to the path withoutCDN makes more sense to me.  Is there a use-case for including the full CDN URLs in the asset manifest?

**Comment by jschroe212** [comment] 2023-08-02 19:41
https://github.com/shakacode/shakapacker/blob/cdf32835d3e0949952b8b4b53063807f714f9b24/package/environments/base.js#L66

**Closed** 2024-05-17 04:41 UTC
Labels: bug
